---
connection:
  :server: irc.freenode.net
  :port: 6667
  :nick: smf_bot
  :delay_joins: :identified
  :channels:
    - "#beginrescueend"
    - "#railsinstaller"
    - "#rubygems-bundler"
    - "#rvm"
    - "#rvm-test"
    - "#smf.sh"
plugins:
  "Cinch::Plugins::Identify":
    :type: :nickserv
    :username: "smf_bot"
    :password: ".password"
  "Cinch::Plugins::Deploy":
    :configurations:
      - :users:
          - mpapis
          - travis-ci
        :channels:
          - '#rvm-test'
        :trigger: '.*rvm/rvm-site.*The build (passed|was fixed).*'
        :command: '~/site/bin/deploy.sh'
  "Cinch::Plugins::YamlMemo":
  "Cinch::Plugins::YamlScore":
  "Cinch::Plugins::UrlScraper":
  "Cinch::Plugins::YamlKeywords":
